name: Test GitLab Stats

on:
  workflow_dispatch:

jobs:
  gitlab-stats:
    runs-on: ubuntu-latest

    env:
      GITLAB_SERVER_URL: ${{ vars.GITLAB_SERVER_URL }}
      GITLAB_PAT: ${{ secrets.GITLAB_PAT }}

    steps:
      - name: Install gitlab-stats
        run: |
          gh extension install mona-actions/gh-gitlab-stats
          gh gitlab-stats --help

      - name: Generate GitLab stats
        run: |
          gh gitlab-stats \
            --hostname "$GITLAB_SERVER_URL" \
            --token "$GITLAB_PAT" \
            --namespace cloud-team
